## @file
#  Main Azure Pipielines YML files for TianoCore EDK II builds.
#
#  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

trigger:
  branches:
    include:
      - patchset/*

jobs:
  - template: AzurePipelines/DoEdk2Build.yml
    parameters:
      git_commands: |
        git clone --depth=1 https://github.com/mdkinney/edk2-platforms.git -b Review_Stratix10_v6
        git clone --depth 1 https://github.com/tianocore/edk2.git
      packages_path_list:
      - 'edk2'
      - 'edk2-platforms'
      build_target_list:
      - 'DEBUG'
      - 'RELEASE'
      - 'NOOPT'
      packages_build_list:
      - 'Platform/Intel/Stratix10/Stratix10SoCPkg.dsc -a AARCH64 -v'
