## @file
#  Main Azure Pipielines YML files for TianoCore EDK II builds.
#
#  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

trigger:
  branches:
    include:
      - patchset/*

jobs:
  - template: AzurePipelines/DoEdk2Build.yml
    parameters:
      build_target_list:
      - 'DEBUG'
      - 'RELEASE'
      - 'NOOPT'
      packages_build_list:
      - 'OvmfPkg/OvmfPkgIa32X64.dsc -a IA32 -a X64 -D SMM_REQUIRE -D DEBUG_ON_SERIAL_PORT -D SOURCE_DEBUG_ENABLE'
      - 'OvmfPkg/OvmfPkgIa32.dsc    -a IA32        -D SMM_REQUIRE -D DEBUG_ON_SERIAL_PORT -D SOURCE_DEBUG_ENABLE'
      - 'OvmfPkg/OvmfPkgX64.dsc             -a X64 -D SMM_REQUIRE -D DEBUG_ON_SERIAL_PORT -D SOURCE_DEBUG_ENABLE'
      - 'OvmfPkg/OvmfPkgIa32X64.dsc -a IA32 -a X64 -D SMM_REQUIRE -D SECURE_BOOT_ENABLE -D TPM2_ENABLE -D TPM2_CONFIG_ENABLE -D NETWORK_TLS_ENABLE -D NETWORK_IP6_ENABLE -D NETWORK_HTTP_BOOT_ENABLE'
      - 'OvmfPkg/OvmfPkgIa32.dsc    -a IA32        -D SMM_REQUIRE -D SECURE_BOOT_ENABLE -D TPM2_ENABLE -D TPM2_CONFIG_ENABLE -D NETWORK_TLS_ENABLE -D NETWORK_IP6_ENABLE -D NETWORK_HTTP_BOOT_ENABLE'
      - 'OvmfPkg/OvmfPkgX64.dsc             -a X64 -D SMM_REQUIRE -D SECURE_BOOT_ENABLE -D TPM2_ENABLE -D TPM2_CONFIG_ENABLE -D NETWORK_TLS_ENABLE -D NETWORK_IP6_ENABLE -D NETWORK_HTTP_BOOT_ENABLE'
