## @file
#  Main Azure Pipielines YML files for TianoCore EDK II builds.
#
#  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

trigger:
  branches:
    include:
      - patchset/*

jobs:
  - template: AzurePipelines/DoEdk2Build.yml
    parameters:
      git_commands: |
        git clone --depth 1 https://github.com/mdkinney/edk2.git -b Bug_162_2055_2056_EmulatorPkg_FixVs20xxBoot_SimplyBuildConfig_V4
      x11_prerequisite: 'true'
      build_target_list:
      - 'DEBUG'
      - 'RELEASE'
      - 'NOOPT'
      packages_build_list:
      - 'EmulatorPkg/EmulatorPkg.dsc -a IA32'
      - 'EmulatorPkg/EmulatorPkg.dsc -a X64'
