## @file
#  Main Azure Pipielines YML files for TianoCore EDK II builds.
#
#  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

trigger:
  branches:
    include:
      - patchset/*

jobs:
  - template: AzurePipelines/DoEdk2Build.yml
    parameters:
      git_commands: |
        git clone --depth=1 https://github.com/tianocore/edk2-platforms.git
        git clone --depth=1 https://github.com/tianocore/edk2-non-osi.git
        git clone --depth 1 https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init
      packages_path_list:
      - 'edk2'
      - 'edk2-platforms/Silicon/Intel'
      - 'edk2-platforms/Platform/Intel'
      - 'edk2-non-osi/Silicon/Intel'
      build_target_list:
      - 'DEBUG'
      - 'RELEASE'
      packages_build_list:
      - 'QuarkPlatformPkg/QuarkMin.dsc -a IA32'
      - 'QuarkPlatformPkg/Quark.dsc -a IA32 -D SECURE_BOOT_ENABLE -D MEASURED_BOOT_ENABLE -D TPM_12_HARDWARE=ATMEL_I2C'
      - 'Vlv2TbltDevicePkg/PlatformPkgX64.dsc  -a IA32 -a X64'
      - 'Vlv2TbltDevicePkg/PlatformPkgIA32.dsc -a IA32'
