## @file
#  Main Azure Pipielines YML files for TianoCore EDK II builds.
#
#  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

trigger:
  branches:
    include:
      - patchset/*

jobs:
  - template: AzurePipelines/DoEdk2Build.yml
    parameters:
      git_commands: |
        git clone --depth 1 https://github.com/mdkinney/edk2.git -b Bug_xxx_FixPackageDependencies
        cd edk2
        git submodule update --init
      build_target_list:
      - 'DEBUG'
      packages_build_list:
      - 'ArmPkg\ArmPkg.dsc'
      - 'ArmPlatformPkg\ArmPlatformPkg.dsc'
      - 'CryptoPkg\CryptoPkg.dsc'
      - 'DynamicTablesPkg\DynamicTablesPkg.dsc'
      - 'EmbeddedPkg\EmbeddedPkg.dsc'
      - 'FatPkg\FatPkg.dsc'
      - 'FmpDevicePkg\FmpDevicePkg.dsc'
      - 'IntelFsp2Pkg\IntelFsp2Pkg.dsc'
      - 'IntelFsp2WrapperPkg\IntelFsp2WrapperPkg.dsc'
      - 'MdeModulePkg\MdeModulePkg.dsc'
      - 'MdePkg\MdePkg.dsc'
      - 'NetworkPkg\NetworkPkg.dsc'
      - 'PcAtChipsetPkg\PcAtChipsetPkg.dsc'
      - 'SecurityPkg\SecurityPkg.dsc'
      - 'ShellPkg\ShellPkg.dsc'
      - 'SignedCapsulePkg\SignedCapsulePkg.dsc'
      - 'SourceLevelDebugPkg\SourceLevelDebugPkg.dsc'
      - 'StandaloneMmPkg\StandaloneMmPkg.dsc'
      - 'UefiCpuPkg\UefiCpuPkg.dsc'
