## @file
#  Main Azure Pipielines YML files for TianoCore EDK II builds.
#
#  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

trigger:
  branches:
    include:
      - patchset/*

jobs:
  - template: AzurePipelines/DoEdk2Build.yml
    parameters:
      git_commands: |
        git clone --depth 1 https://github.com/mdkinney/edk2.git -b BZ_none_EmulatorPkg_Fixes_V2
      x11_prerequisite: 'true'
      build_target_list:
      - 'DEBUG'
      - 'RELEASE'
      linux_packages_build_list:
      - 'EmulatorPkg/EmulatorPkg.dsc -a IA32 -D UNIX_SEC_BUILD'
      - 'EmulatorPkg/EmulatorPkg.dsc -a X64  -D UNIX_SEC_BUILD'
      windows_packages_build_list:
      - 'EmulatorPkg/EmulatorPkg.dsc -a IA32 -D WIN_SEC_BUILD'
      - 'EmulatorPkg/EmulatorPkg.dsc -a X64  -D WIN_SEC_BUILD'
